### PR TITLE
expired context cleanup #280

### PR DESCRIPTION
**Pull request by sadeghte**

### CODE REVIEW

**Comment by bakhshandeh** [comment]
https://github.com/muon-protocol/muon-node-js/blob/df84e3ed43c405ad619eb07c9c3b98999baa4565/src/core/plugins/db-synchronizer.ts#L431-L432

What happens when this code runs in the middle of a reshare?
Let's assume an app is rotated but not reshared. This code will remove the context and the keygen step for rotation will fail.

Is that right?

**Comment by bakhshandeh** [comment]
https://github.com/muon-protocol/muon-node-js/blob/df84e3ed43c405ad619eb07c9c3b98999baa4565/src/core/plugins/db-synchronizer.ts#L429-L430

Is this a problem when a deployer is not synced?
This scenario:
1- deployer A is not synced and context is not saved on it yet
2- non deployer B calls A to confirm that the context should be removed
3- A returns true and the context will be removed on B

**Comment by sadeghte** [comment]
> https://github.com/muon-protocol/muon-node-js/blob/df84e3ed43c405ad619eb07c9c3b98999baa4565/src/core/plugins/db-synchronizer.ts#L431-L432
> 
> This condition will cause the deployers that do not receive the reshare request to keep the contexts indefinitely. Is that correct? Can we check and remove the context if it is expired and reshared?

This checking tries to keep the contexts that have a problem and are rotated but not reshared. If resharing is completed on other deployers, it will propagate using db-sync and the current node will receive the reshare request. Only the contexts that are not reshared at all will remain forever.

**Comment by sadeghte** [comment]
> https://github.com/muon-protocol/muon-node-js/blob/df84e3ed43c405ad619eb07c9c3b98999baa4565/src/core/plugins/db-synchronizer.ts#L429-L430
> 
> Is this a problem when a deployer is not synced? This scenario: 1- deployer A is not synced and context is not saved on it yet 2- non deployer B calls A to confirm that the context should be removed 3- A returns true and the context will be removed on B

If a deployer is not synced, it will not respond to the non-deployer node. Therefore, the non-deployer nodes will receive responses only from synced deployers.

**Pull request merged**
